# Generated by Django 4.1.5 on 2023-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=25)),
                ('mod_name', models.CharField(max_length=25)),
                ('mod_action', models.CharField(max_length=20)),
                ('mod_link', models.URLField()),
                ('mod_time', models.DateTimeField()),
                ('mod_item', models.TextField()),
            ],
        ),
    ]
