# Generated by Django 4.1.5 on 2023-01-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlogs', '0002_modlog_sub_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modlog',
            name='unique_id',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
