# Generated by Django 4.1.5 on 2023-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlogs', '0003_modlog_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modlog',
            name='mod_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
