# Generated by Django 4.1.5 on 2023-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlogs', '0007_alter_modlog_mod_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modlog',
            name='mod_time',
            field=models.DateTimeField(),
        ),
    ]
