# Generated by Django 4.1.5 on 2023-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlogs', '0008_alter_modlog_mod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modlog',
            name='sub_user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='modlog',
            name='unique_id',
            field=models.CharField(max_length=120),
        ),
    ]
